//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPhase1
    {
        public int inPhase1ID { get; set; }
        public string stPrimaryURL { get; set; }
        public string stURLInnerText { get; set; }
        public Nullable<bool> flgIsCompleted { get; set; }
        public Nullable<System.DateTime> dtCreatedOn { get; set; }
    }
}
